### ISSUE TITLE
Using same code for Adjuster and Props

### ISSUE THREAD

**Issue by LeonaMorro** [nPoseTeam/nPose-V3#1]
Currently Adjusters will only rezz inside the 10m radius.

**Comment by HowardBaxton** [comment]
Currently the slave rezzes Adjusters and the Core rezzes props.  The core has the listener which watches for both Adjuster messages and PROP messages.  The Core processes and reports to chat out for the owner all the PROP stuff.  The Core listens for Adjuster messages and forwards them to the Slave for processing.

Differences of PROP reporting and Adjuster reporting:
    1)  The PROP reporting only needs to repeat a new position/rotation to the Owner and the Adjuster not only needs to also report to the Owner but has to move the AV to this new position/rotation.
    2)  The info chatted to the Owner for a PROP move begins the chat line with "ROP|', and  the Adjuster needs to begin this report line with "ANIM|" plus send a warning (reminder) to the owner that this may be a SCHMO/SCHMOE line and to copy/paste accordingly.
    3)  PROPs have a 1.0 second sleep between rez and move because they are more complexed and need more time to rez and get scripts up and running.  Adjusters can work with 0.1 second delay.

Differences of PROP rezzing and Adjuster rezzing:
    1)  Rezzing a PROP is a single line process where only one PROP is rezzed at a time and done in ProcssLine funtion of the Core as this rez command comes from NC data.  Rezzing Adjusters are fired off internally and must step through the Slots list and rez an Adjuster for each stride (seat) in the Slots list.
    2)  The life span and rezzing rules for a PROP are that they live only as long as a pose set (normal) or stay rezzed until specifically told to die (explicit) and Adjusters are basically turned on or off.  If on, the Adjusters must de-rez and re-rez with each pose set change to use current positions/rotations.
    3)  PROP rezzing sends two params MX'd into rez params (quiet and explicit) and the Adjuster rezzing sends only one param (iMoved) which is set to 1 for Adjusters being rezzed within 10 meters and 0 if it needs to be moved beyond 10 meters..

Advantages:

Disadvantages:
    1)  An additional script in the Adjuster prim.
    2)  Prop rezzing must be moved from the ProcessLine function to a new function.
    3)  The entire process of rezzing Adjusters has to be moved to this new PROP rezzing function with very few (if any) things in common which could be combined.
    4)  This combined effort will make reading the script far more difficult to follow.
    5)  Change the scripts to act on PROPRELAY.
    6)  Since all this would take place in the Core script, some message must be sent to the Slave to update positions/rotations when an Adjuster is moved.  Alternatively let the Slave do what it has always done and process the Adjuster messages there with some modifications.

**Comment by HowardBaxton** [comment]
As I have seen attempting to use this approach with the Admin Hud, the Adjusters would also be reported as props when a PosDump is done with Adjusters rezzed.  It would also make Adjuster version roll susceptible to any changes in the Prop Plugin.  Both of these issues will lead to user confusion.

**Comment by LeonaMorro** [comment]
Howard is right, this doesn't make sense.
