### ISSUE TITLE
Multiple SAT and NOTSAT lines are added to Slots list with SCHMO

### ISSUE THREAD

**Issue by HowardBaxton** [nPoseTeam/nPose-V3#15]
If there are 2 or more SCHMO lines in a notecard where each have SATMSG or NOTSATMSG lines, only the menu user's slot should have new SAT and NOTSAT updates.  The current result is that all slot strides read and process the msg lines.

The problem arises because the SCHMO line is run separately from the SATMSG and NOTSATMSG lines.  The SCHMO lines are working perfectly and only updating the menu user's slot stride.  However the SATMSG lines have an incorrect visibility to only update the menu user's stride and will update every stride's SAT and NOTSAT msg data.

I have built a flag which seems to successfully limit these SCHMO SAT and NOTSAT lines to only the menu user's stride.  This is a mod to the core script only.  I will submit the changed core in a new branch of of the currently released version as a proposed fix for review.  If it is found to be an acceptable fix, I'm hoping it can just be merged into the other branches.

**Comment by LeonaMorro** [comment]
I can confirm this issue. Thank you for the provided code. I appreciate it because it helped a lot to understand the problem. A fix for it should be included in the next version if we can solve the problem. (I'm already testing V3.10 which includes a couple of bugfixes and the multilanguage stuff I talked about several month (or years?) ago)

After testing I guess that a flag based solution can't cover all possibilities.
For example I checked this NC (not sitting on the object):
```
SCHMO|1|meditation|<0,0,0>|<0,0,0>
SCHMOE|2|meditation|<0,0,0>|<0,0,0>
SATMSG|0815|message1|%AVKEY%|1
```
nPose V3.00, slots list
```
meditation^<0.000000, 0.000000, 0.000000>^<0.000000, 0.000000, 0.000000, 1.000000>^^^§0815|message1|%AVKEY%|1^^§seat1§ANIM§.init^
meditation^<0.000000, 0.000000, 0.000000>^<0.000000, 0.000000, 0.000000, 1.000000>^^^^^§seat2§SCHMOE§SET:sit1
```
nPose V3.00 + your fix, slots list
```
meditation^<0.000000, 0.000000, 0.000000>^<0.000000, 0.000000, 0.000000, 1.000000>^^^^^§seat1§ANIM§.init^
meditation^<0.000000, 0.000000, 0.000000>^<0.000000, 0.000000, 0.000000, 1.000000>^^^§0815|message1|%AVKEY%|1^^§seat2§SCHMOE§SET:sit1
```
I guess the code has two bugs a minor one that writes the SATMSG into the wrong slot and a major one that allows the SATMSG to be written into the slots list.

**Comment by HowardBaxton** [comment]
Interesting, I didn't anticipate mixing SCHMO and SCHMOE in same card.  Not sure it makes sense to do this but it is possible to do.  Also it wouldn't make sense to mix ANIM and SCHMO yet it is possible to do. 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: LeonaMorro <notifications@github.com> Date: 9/19/17  7:07 AM  (GMT-08:00) To: nPoseTeam/nPose-V3 <nPose-V3@noreply.github.com> Cc: HowardBaxton <howardbaxton@gmail.com>, Author <author@noreply.github.com> Subject: Re: [nPoseTeam/nPose-V3] Multiple SAT and NOTSAT lines are added to Slots list with SCHMO (#15) 
I can confirm this issue. Thank you for the provided code. I appreciate it because it helped a lot to understand the problem. A fix for it should be included in the next version if we can solve the problem. (I'm already testing V3.10 which includes a couple of bugfixes and the multilanguage stuff I talked about several month (or years?) ago)
After testing I guess that a flag based solution can't cover all possibilities.

For example I checked this NC (not sitting on the object):
SCHMO|1|meditation|<0,0,0>|<0,0,0>
SCHMOE|2|meditation|<0,0,0>|<0,0,0>
SATMSG|0815|message1|%AVKEY%|1

nPose V3.00, slots list
meditation^<0.000000, 0.000000, 0.000000>^<0.000000, 0.000000, 0.000000, 1.000000>^^^§0815|message1|%AVKEY%|1^^§seat1§ANIM§.init^
meditation^<0.000000, 0.000000, 0.000000>^<0.000000, 0.000000, 0.000000, 1.000000>^^^^^§seat2§SCHMOE§SET:sit1

nPose V3.00 + your fix, slots list
meditation^<0.000000, 0.000000, 0.000000>^<0.000000, 0.000000, 0.000000, 1.000000>^^^^^§seat1§ANIM§.init^
meditation^<0.000000, 0.000000, 0.000000>^<0.000000, 0.000000, 0.000000, 1.000000>^^^§0815|message1|%AVKEY%|1^^§seat2§SCHMOE§SET:sit1

I guess the code has two bugs a minor one that writes the SATMSG into the wrong slot and a major one that allows the SATMSG to be written into the slots list.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nPoseTeam/nPose-V3","title":"nPoseTeam/nPose-V3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nPoseTeam/nPose-V3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LeonaMorro in #15: I can confirm this issue. Thank you for the provided code. I appreciate it because it helped a lot to understand the problem. A fix for it should be included in the next version if we can solve the problem. (I'm already testing V3.10 which includes a couple of bugfixes and the multilanguage stuff I talked about several month (or years?) ago)\r\n\r\nAfter testing I guess that a flag based solution can't cover all possibilities.\r\nFor example I checked this NC (not sitting on the object):\r\n```\r\nSCHMO|1|meditation|\u003c0,0,0\u003e|\u003c0,0,0\u003e\r\nSCHMOE|2|meditation|\u003c0,0,0\u003e|\u003c0,0,0\u003e\r\nSATMSG|0815|message1|%AVKEY%|1\r\n```\r\nnPose V3.00, slots list\r\n```\r\nmeditation^\u003c0.000000, 0.000000, 0.000000\u003e^\u003c0.000000, 0.000000, 0.000000, 1.000000\u003e^^^§0815|message1|%AVKEY%|1^^§seat1§ANIM§.init^\r\nmeditation^\u003c0.000000, 0.000000, 0.000000\u003e^\u003c0.000000, 0.000000, 0.000000, 1.000000\u003e^^^^^§seat2§SCHMOE§SET:sit1\r\n```\r\nnPose V3.00 + your fix, slots list\r\n```\r\nmeditation^\u003c0.000000, 0.000000, 0.000000\u003e^\u003c0.000000, 0.000000, 0.000000, 1.000000\u003e^^^^^§seat1§ANIM§.init^\r\nmeditation^\u003c0.000000, 0.000000, 0.000000\u003e^\u003c0.000000, 0.000000, 0.000000, 1.000000\u003e^^^§0815|message1|%AVKEY%|1^^§seat2§SCHMOE§SET:sit1\r\n```\r\nI guess the code has two bugs a minor one that writes the SATMSG into the wrong slot and a major one that allows the SATMSG to be written into the slots list."}],"action":{"name":"View Issue","url":"https://github.com/nPoseTeam/nPose-V3/issues/15#issuecomment-330550933"}}}

**Comment by LeonaMorro** [comment]
ANIM+SCHMO(E) in one card: I can't imagine anything that would require such a combination.

SCHMO + SCHMOE in one card: I don't think it is widely used, but I can imagine some situations where it can be usefull.

Nevertheless both combinations are currently legal.

And yes, the NC is mean. Its only purpose is to fool the code. Sorry for my wickedness ;)

**Comment by LeonaMorro** [comment]
Can we solve the issue by implementing a new placeholder "%AVSEAT%"?
Example usage:

`SATMSG|0815|message|%AVKEY%|%AVSEAT%`

**Comment by HowardBaxton** [comment]
We already have the seat number for SCHMO/SCHMOE and optionally for ANIM.  The %AVSEAT% will not gain anything.  All might work ok if the SCHMO lines follow the SCHMOE/ANIM lines, othwrwise it becomes a logistic challenge. 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: LeonaMorro <notifications@github.com> Date: 9/20/17  6:21 AM  (GMT-08:00) To: nPoseTeam/nPose-V3 <nPose-V3@noreply.github.com> Cc: HowardBaxton <howardbaxton@gmail.com>, Author <author@noreply.github.com> Subject: Re: [nPoseTeam/nPose-V3] Multiple SAT and NOTSAT lines are added to Slots list with SCHMO (#15) 
Can we solve the issue by implementing a new placeholder "%AVSEAT%"?

Example usage:
SATMSG|0815|message|%AVKEY%|%AVSEAT%

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nPoseTeam/nPose-V3","title":"nPoseTeam/nPose-V3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nPoseTeam/nPose-V3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LeonaMorro in #15: Can we solve the issue by implementing a new placeholder \"%AVSEAT%\"?\r\nExample usage:\r\n\r\n`SATMSG|0815|message|%AVKEY%|%AVSEAT%`\r\n"}],"action":{"name":"View Issue","url":"https://github.com/nPoseTeam/nPose-V3/issues/15#issuecomment-330849220"}}}

**Comment by LeonaMorro** [comment]
You wrote: "If there are 2 or more SCHMO lines in a notecard where each have SATMSG or NOTSATMSG lines, only the menu user's slot should have new SAT and NOTSAT updates"

It could be a NC like this:
```
SCHMO|1|meditation|<0,0,0>|<0,0,0>
SATMSG|0815|message||1
SCHMO|2|meditation|<0,0,0>|<0,0,0>
SATMSG|0815|message||2
```
and that is not working as you want.

If we implement a %AVSEAT% placeholder (where %AVSEAT% is filled with the seat number of the menu user), your NC could look like this:
```
SCHMO|1|meditation|<0,0,0>|<0,0,0>
SCHMO|2|meditation|<0,0,0>|<0,0,0>
SATMSG|0815|message||%AVSEAT%
```
and it does exaclty what you want. Without any fix.
My question was: Would this solve your initial problem? (Because I know that this "workaround" is not as good as a real fix, but a real fix seams to be very complex.)

**Comment by HowardBaxton** [comment]
These lines in a notecard do work with the mods I added:
SCHMO|1|meditation|<0,0,0>|<0,0,0>
SATMSG|0815|message||1
SCHMO|2|meditation|<0,0,0>|<0,0,0>
SATMSG|0815|message||2 The %AVSEAT% would not change the need for the mods I made to control when the nessage is processed.  Sorry if I was not clear in my response.  It would also make the SATMSG association to the correct seat very difficult and add that extra burden to the complexity.
Maybe I do not see how this would solve both issues that you are thinking of.  How would we get the wildcard replacement?  How woild we use the replacement to ensure SATMSG lines only get added for SCHMO when the menu users seat is processed?
Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: LeonaMorro <notifications@github.com> Date: 9/20/17  10:48 AM  (GMT-08:00) To: nPoseTeam/nPose-V3 <nPose-V3@noreply.github.com> Cc: HowardBaxton <howardbaxton@gmail.com>, Author <author@noreply.github.com> Subject: Re: [nPoseTeam/nPose-V3] Multiple SAT and NOTSAT lines are added to Slots list with SCHMO (#15) 
You wrote: "If there are 2 or more SCHMO lines in a notecard where each have SATMSG or NOTSATMSG lines, only the menu user's slot should have new SAT and NOTSAT updates"
It could be a NC like this:
SCHMO|1|meditation|<0,0,0>|<0,0,0>
SATMSG|0815|message||1
SCHMO|2|meditation|<0,0,0>|<0,0,0>
SATMSG|0815|message||2

and that is not working as you want.
If we implement a %AVSEAT% placeholder (where %AVSEAT% is filled with the seat number of the menu user), your NC could look like this:
SCHMO|1|meditation|<0,0,0>|<0,0,0>
SCHMO|2|meditation|<0,0,0>|<0,0,0>
SATMSG|0815|message||%AVSEAT%

and it does exaclty what you want. Without any fix.

My question was: Would this solve your initial problem? (Because I know that this "workaround" is not as good as a real fix, but a real fix seams to be very complex.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nPoseTeam/nPose-V3","title":"nPoseTeam/nPose-V3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nPoseTeam/nPose-V3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LeonaMorro in #15: You wrote: \"If there are 2 or more SCHMO lines in a notecard where each have SATMSG or NOTSATMSG lines, only the menu user's slot should have new SAT and NOTSAT updates\"\r\n\r\nIt could be a NC like this:\r\n```\r\nSCHMO|1|meditation|\u003c0,0,0\u003e|\u003c0,0,0\u003e\r\nSATMSG|0815|message||1\r\nSCHMO|2|meditation|\u003c0,0,0\u003e|\u003c0,0,0\u003e\r\nSATMSG|0815|message||2\r\n```\r\nand that is not working as you want.\r\n\r\nIf we implement a %AVSEAT% placeholder (where %AVSEAT% is filled with the seat number of the menu user), your NC could look like this:\r\n```\r\nSCHMO|1|meditation|\u003c0,0,0\u003e|\u003c0,0,0\u003e\r\nSCHMO|2|meditation|\u003c0,0,0\u003e|\u003c0,0,0\u003e\r\nSATMSG|0815|message||%AVSEAT%\r\n```\r\nand it does exaclty what you want. Without any fix.\r\nMy question was: Would this solve your initial problem? (Because I know that this \"workaround\" is not as good as a real fix, but a real fix seams to be very complex.)"}],"action":{"name":"View Issue","url":"https://github.com/nPoseTeam/nPose-V3/issues/15#issuecomment-330928896"}}}

**Comment by LeonaMorro** [comment]
I guess you are working on an concrete project? Can you give it to me so that I can have a look?

**Comment by HowardBaxton** [comment]
Been working on this in InWorldz with a iser who is good enough to pish nPose when it comes to the SATMSG stuff.  I have a copy of what she is working on but it is not transferable.  Maybe I can mock something together to show.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: LeonaMorro <notifications@github.com> Date: 9/21/17  6:21 AM  (GMT-08:00) To: nPoseTeam/nPose-V3 <nPose-V3@noreply.github.com> Cc: HowardBaxton <howardbaxton@gmail.com>, Author <author@noreply.github.com> Subject: Re: [nPoseTeam/nPose-V3] Multiple SAT and NOTSAT lines are added to Slots list with SCHMO (#15) 
I guess you are working on an concrete project? Can you give it to me so that I can have a look?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nPoseTeam/nPose-V3","title":"nPoseTeam/nPose-V3","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nPoseTeam/nPose-V3"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LeonaMorro in #15: I guess you are working on an concrete project? Can you give it to me so that I can have a look? "}],"action":{"name":"View Issue","url":"https://github.com/nPoseTeam/nPose-V3/issues/15#issuecomment-331154388"}}}

**Comment by LeonaMorro** [comment]
with the command permission added in f4d1e06e35c3e6b9159160e458a55489a614a760 we will be able to solve the issue.
