### ISSUE TITLE
Adjuster Reporting Issue

### ISSUE THREAD

**Issue by HowardBaxton** [nPoseTeam/nPose-V3#17]
While chatting new positions to local and also support moving the slave script to another linked prim the slave always assumes there is a linked set when it tries to grab the root prim name and saves the name of linked prim 1.  This creates an issue for single prim builds as the root prim here is 0 and prim 1 doesn't exist.

This is the same for the Dump function.

**Comment by HowardBaxton** [comment]
llGetObjectName() will return the name of the prim that the slave resides in.  However if the slave is in a separate linked prim, it will not be the prim that the notecards are in.  It seems this is a waste of effort as it could miss-lead the builder to the wrong prim anyway.  My vote is to remove this code completely and just use the object name.

**Comment by LeonaMorro** [comment]
I also vote for removing this piece of code.
