### ISSUE TITLE
Playing Animations Sequentilally

### ISSUE THREAD

**Issue by spflanze** [nPoseTeam/nPose-V3#21]
I have been able to play animations sequentialy with a Set: notecard contents such as this:

`TIMER|myTimer| 0 |ANIM|LPS01|<0.525318, 0.0000, 0.100>|<0.000000, -90.000000, -180.000000>
TIMER|myTimer| 8.917 |ANIM|LPS02|<0.525318, 0.0000, 0.100>|<0.000000, -90.000000, -180.000000>
TIMER|myTimer| 20.167 |ANIM|LPS03|<0.525318, 0.0000, 0.100>|<0.000000, -90.000000, -180.000000>
TIMER|myTimer| 65.833 |TIMER_REMOVE`

Because I created these animations in Blender I know exactly how long they last, and so I can schedule them to play sequentially using the timer as demonstrated above.

But there are problems. It does not happen every time, but very often when an animations transitions from a just ended one to the next the avatar is very briefly dislocated from the position it was intended to be in. It looks to me like lag regarding reading the next position and orientation vectors. What I think is a manifestation of the same problem is on first sitting when the default animation plays. The first instant my avatar is horizontal above ground with its feet on the sit object's origin point. This seems to last for only one or maybe just a few animation frames, and them the avatar is positioned where it is expected to be.

Is there a solution to this? Is there a better way to play the animations sequentially?

Since in the above example the position and orientation vectors are the same for every animation it seems wasteful of script execution time to set the same again for subsequent animations in the sequence. An option not to have this might be a way to solve this for between animations in future nPoser versions.

**Comment by LeonaMorro** [comment]
@spflanze 
Does this solve your problem? Can I close this issue?

**Comment by LeonaMorro** [comment]
@spflanze 
If this doesn't fix your problem you can reopen this.
