### ISSUE TITLE
Slots list does not return to a known state when 2default=1

### ISSUE THREAD

**Issue by LeonaMorro** [nPoseTeam/nPose-V3#7]
Howard wrote:
I found a couple places where the default card is run and the Slots list needed to be cleared as well as SlotMax needed to be set to zero.
see see 5a97170c7cfcc1444b6a527671575760b2ff9f5b

**Comment by LeonaMorro** [comment]
If the default card contains an ANIM line the Slots list will be cleared while reading the default card (when we fixed #6) .. Ins't that enough?

**Comment by HowardBaxton** [comment]
It becomes needed if we allow SCHMOE to be used in the default.

**Comment by LeonaMorro** [comment]
You are right. If we allow SCHMOE to be used instead of an ANIM command to build a slot. we may have to do that.

**Comment by LeonaMorro** [comment]
We are not modifying the SCHMO(E) commands recently, so I close this issue. Reopen it when needed.
