### ISSUE TITLE
chatchannel is broadcasted via link message every time nPose sees a new sitter

### ISSUE THREAD

**Issue by LeonaMorro** [nPoseTeam/nPose-V3#8]
Howard wrote:
I also noticed the chatchannel is broadcasted via link message every time nPose sees a new sitter.  I'm not sure this is required for proper functioning of the program but I guess it isn't hurting anything.  We can remove that instruction from the Changed event or leave it, I'm open to suggestions.

**Comment by LeonaMorro** [comment]
I also don't see any need for the brodcast and I vote for removing it (less code & less events)

**Comment by HowardBaxton** [comment]
In all other situations such as prop rezzing or temp attach the chatchannel
is handled.  I cannot think of any reason this is needed.  I am in
agreement with removing this broadcast.
